### ISSUE TITLE
import request出错

### ISSUE THREAD

**Issue by notice501** [ianva/vim-youdao-translater#1]
hi，我写了篇博客介绍了你的插件
[每天一个vim插件–有道翻译](http://foocoder.com/blog/mei-tian-%5B%3F%5D-ge-vimcha-jian-you-dao-fan-yi.html/)
有个用户评论遇到问题：

    你好，我使用时为什么显示“ImportError: No module named requests”，当然也不能使用这个插件。我的环境是服务器集群普通用户，自己安装的Python 3.3，设置了LD_LIBRARY_PATH和PATH，又用源码安装了requests，在shell中，$python,import requests,是可以正常使用requests的。

**Comment by rambo-panda** [comment]
是不支持2.6吗？

**Comment by ianva** [comment]
没具体测试，本机是 2.7 的

**Comment by wsdjeg** [comment]
如果是ubuntu系统建议不要使用pip安装软件,自带的apt管理器可以更好的和本地兼容,我安装了后没有任何问题

**Comment by wsdjeg** [comment]
如果是python2,7 请使用这个命令 sudo apt-get install python-requests

**Comment by wsdjeg** [comment]
如果是python3 请使用sudo apt-get install python3-requests

**Comment by JamesKid** [comment]
linux python2.6.6会报错，装了python2.7  会影响ibus输入法，，，郁闷了，，

**Comment by wsdjeg** [comment]
刚在arch下测试了这个插件，arch下需要:
`sudo pacman -S python2-requests`

**Comment by ianva** [comment]
thanks for @jicong

**Comment by wsdjeg** [comment]
移除依赖了？

**Comment by ianva** [comment]
对，@jicong 提交了一个 pull request，移除了相关依赖，并添加了一些功能，已经 merge，并发了 2.2.0 版

**Comment by wsdjeg** [comment]
太赞了，这是我最常用的插件

**Comment by ianva** [comment]
哈哈，你可以感谢他下

**Comment by wsdjeg** [comment]
@jicong 谢谢你为此差价提交的更新

**Comment by jicong** [comment]
这也是我这种英语捉急的人经常用的插件，所以就改进了一下。希望能有更多人用起来。
