### ISSUE TITLE
这个插件如何安装

### ISSUE THREAD

**Issue by GH1995** [ianva/vim-youdao-translater#13]
您好，我按照`README`复制了文件，但是`<C-t>`显示**不是编辑器的命令**`:Ydc`。这个插件应该如何安装呢？麻烦您哈

**Comment by ianva** [comment]
安装方式是什么？说下系统环境，贴下报错信息

**Comment by GH1995** [comment]
我选择了普通安装，启动时是这样报错
```
➜  ~ vim ~/.vimrc 
Error: Required vim compiled with +python
请按 ENTER 或其它命令继续
```
<C-T>报错如下
```
E73: tag 堆栈为空
```
PS：系统环境为Ubuntu 16.04 64位，vmware

**Comment by ianva** [comment]
应该是 vim 编译的时候没有添加 python 的选项

**Comment by GH1995** [comment]
嗯，您好，`echo has('python')`已经可以返回`1`了，但是当我`<C-t>`时错误信息不变，期待您的进一步回复。

**Comment by GH1995** [comment]
您好，问题已经解决。
