### ISSUE TITLE
异步

### ISSUE THREAD

**Issue by CPPCOCOS2DX** [ianva/vim-youdao-translater#18]
自己刚使用了下这个插件,能够满足在看VIM文档时候遇到单词需要翻译的基本需求.但因为VIM8.0已经支持异步,所以我想问下这个插件能不能改成异步的,这样就比较完美了.

**Comment by hiberabyss** [comment]
Also need this feature, is there any plan?

Thanks!

**Comment by CPPCOCOS2DX** [comment]
Sorry! No Plan! I Do't Get The Solution.If You Have ,Please Tell Me! THX!

**Comment by ianva** [comment]
Thanks for @hiberabyss contribute the new feature to share with everyone.

**Comment by ianva** [comment]
Thanks for @hiberabyss contribute the new feature to share with everyone.
