### ISSUE TITLE
neovim中报错不能使用

### ISSUE THREAD

**Issue by awerdx520** [ianva/vim-youdao-translater#26]
#### 运行环境
- deepin 15.5
- neovim 0.1.7
- vim-plug

#### 问题
1. 在neovim中不能运行，vim8中可以
2. 打开nvim时会出现
```
Error detected while processing /home/xxx/.vim/plugged/vim-youdao-translater/plugin/ydt.vim:
line    7:
E729: using Funcref as a String
E475: Invalid argument: 
Press ENTER or type command to continue
```
3.按下快捷键Ctrl-t后出现
```
Error detected while processing function <SNR>41_YoudaoCursorTranslate[1]..4:
line  9:
Argument is not a function or function name
```

**Comment by ianva** [comment]
请暂时切换到 2.5.1 版本，2.6.0 目前处于 pre-release.
@hiberabyss

**Comment by hiberabyss** [comment]
@awerdx520 可能是因为 neovim 版本太低了, 能不能升级到比较新的 neovim 版本看有没有问题?

**Comment by ianva** [comment]
@hiberabyss 能基于 feature 做判断而不基于版本使用异步这个功能么，包括 macvim，如果可以的化改进一下

**Comment by hiberabyss** [comment]
@ianva macvim 现在是已经做了判断了, neovim 的话等有时间的时候看一下.
