### ISSUE TITLE
neovim中visual模式翻译错误

### ISSUE THREAD

**Issue by awerdx520** [ianva/vim-youdao-translater#27]
####环境
- OS: deepin 15.5
- neovim 0.2.2
- vim-plug
####问题
- 在`visual`模式下，我使用`$`命令选择一行，再`Ctrl-T`后显示：
```
有道翻译查询出错
```
- 在`normal`/`insert`模式下运行正常，`visual`模式下单词都不能查询。

**Comment by ianva** [comment]
这个功能基本废弃掉了，只能查询单词，因为这个翻译的接口有道已经移除了，后面会看看其他接口能不能做
