### ISSUE TITLE
vim 7.x 兼容

### ISSUE THREAD

**Issue by ZSaberLv0** [ianva/vim-youdao-translater#28]
能否保持对 vim 7.x 的兼容? 有些旧环境升 vim 8 还是比较麻烦的

目前的问题:

```
Error detected while processing /root/.vim/bundle/vim-youdao-translater/plugin/ydt.vim:
line    2:
E121: Undefined variable: v:true
E15: Invalid expression: {'stdout_buffered': v:true, 'stderr_buffered': v:true}
line    4:
E121: Undefined variable: s:translator
line    5:
E121: Undefined variable: a:data
E116: Invalid arguments for function empty(a:data) | echo join(a:data) | endif
E15: Invalid expression: !empty(a:data) | echo join(a:data) | endif
line    6:
E193: :endfunction not inside a function
line    7:
E121: Undefined variable: s:translator
E116: Invalid arguments for function function(s:translator.on_stdout)
E15: Invalid expression: function(s:translator.on_stdout)
line    9:
E121: Undefined variable: s:translator
line   13:
E133: :return not inside a function
line   16:
E121: Undefined variable: a:lines
E116: Invalid arguments for function printf("%s %s %s", python_cmd, s:translator_file, a:lines)
E15: Invalid expression: printf("%s %s %s", python_cmd, s:translator_file, a:lines)
line   18:
E133: :return not inside a function
line   20:
E133: :return not inside a function
line   24:
E193: :endfunction not inside a function
```

**Comment by ianva** [comment]
暂时切换到 2.5.1 版

**Comment by ZSaberLv0** [comment]
@ianva 新版本是否有计划继续保持 vim 7.x 的兼容? 如果没有, 建议保留旧版本的分支 (而不是只在 release 里面有), 否则插件管理不太方便, 谢谢

**Comment by ZSaberLv0** [comment]
@ianva 用 vim-plug 安装, 除按键映射外没有其他配置

Python 2.6.6

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 21 2016 17:10:41)
Included patches: 1-207, 209-629
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
```

**Comment by pinggit** [comment]
我也是用vim-plug的安装方式。vim8。每次必现。。。

**Comment by pinggit** [comment]
root@server1:~# vim
Error detected while processing /root/.vim/bundle/vim-youdao-translater/plugin/ydt.vim:
line    2:
E121: Undefined variable: v:true
E15: Invalid expression: {'stdout_buffered': v:true, 'stderr_buffered': v:true}
line    4:
E121: Undefined variable: s:translator
line    5:
E121: Undefined variable: a:data
E116: Invalid arguments for function empty(a:data) | echo join(a:data) | endif
E15: Invalid expression: !empty(a:data) | echo join(a:data) | endif
line    6:
E193: :endfunction not inside a function
line    7:
E121: Undefined variable: s:translator
E116: Invalid arguments for function function(s:translator.on_stdout)
E15: Invalid expression: function(s:translator.on_stdout)
line    9:
E121: Undefined variable: s:translator
line   13:
E133: :return not inside a function
line   16:
E121: Undefined variable: a:lines
E116: Invalid arguments for function printf("%s %s %s", python_cmd, s:translator_file, a:lines)
E15: Invalid expression: printf("%s %s %s", python_cmd, s:translator_file, a:lines)
line   18:
E133: :return not inside a function
line   20:
E133: :return not inside a function
line   24:
E193: :endfunction not inside a function
line    2:
E121: Undefined variable: v:true
E15: Invalid expression: {'stdout_buffered': v:true, 'stderr_buffered': v:true}
line    4:
E121: Undefined variable: s:translator
line    5:
E121: Undefined variable: a:data
E116: Invalid arguments for function empty(a:data) | echo join(a:data) | endif
E15: Invalid expression: !empty(a:data) | echo join(a:data) | endif
line    6:
E193: :endfunction not inside a function
line    7:
E121: Undefined variable: s:translator
E116: Invalid arguments for function function(s:translator.on_stdout)
E15: Invalid expression: function(s:translator.on_stdout)
line    9:
E121: Undefined variable: s:translator
line   13:
E133: :return not inside a function
line   16:
E121: Undefined variable: a:lines
E116: Invalid arguments for function printf("%s %s %s", python_cmd, s:translator_file, a:lines)
E15: Invalid expression: printf("%s %s %s", python_cmd, s:translator_file, a:lines)
line   18:
E133: :return not inside a function
line   20:
E133: :return not inside a function
line   24:
E193: :endfunction not inside a function
Press ENTER or type command to continue
···

**Comment by VoldikSS** [comment]
@pinggit 真的是 Vim8 吗？这个 `v:true` 变量是 [patch 7.4.1154 ](https://github.com/vim/vim/commit/65591001e405cbaaf9772c9375d0bb6049cf9a3a) 里面加上的，Vim8 应该不会出现这个问题。
另外，其实 Neovim 很好用的。

**Comment by pinggit** [comment]
你说的没错。抱歉我看错了。版本是：
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)

请问这个有什么办法解决吗？
我有很多vim7.4的系统安装这个插件报错。
谢谢！

**Comment by VoldikSS** [comment]
建议升级，Vim74 太老了，现在好多插件都需要 Vim8 的异步特性，要么升 Vim8，要么试试 Neovim

pinggit <notifications@github.com> 于 2018年10月6日周六 下午12:06写道：
