### ISSUE TITLE
貌似wsl中不能用

### ISSUE THREAD

**Issue by pinggit** [ianva/vim-youdao-translater#30]
这个插件在cygwin和ubuntu1804下都是好的。
但很奇怪在wsl （windows subsystem linux）ubuntu1804下不能用。
查了半天看不出问题。
:Ydc 没有任何输出。
有啥线索？

**Comment by ianva** [comment]
我这边没有环境测试，你先切一下不同的版本试试 v.2.5.1

**Comment by VoldikSS** [comment]
@pinggit 建议先单独运行 https://github.com/ianva/vim-youdao-translater/blob/master/youdao.py 试试，记得把 
```vim
info = get_word_info(str_decode(string.join(argv[1:])))
```
改为
```vim
info = get_word_info(str_decode("test"))
```
好多情况是这个 py 文件出错的。
