### ISSUE TITLE
安装了无法使用啊

### ISSUE THREAD

**Issue by limbo-envoy** [ianva/vim-youdao-translater#32]
E492: 不是编辑器的命令: Ydc

**Comment by VoldikSS** [comment]
添加 ~/.vimrc 文件：
```vim
vnoremap <silent> <C-T> :<C-u>Ydv<CR>
nnoremap <silent> <C-T> :<C-u>Ydc<CR>
noremap <leader>yd :<C-u>Yde<CR>
```
做了没

**Comment by limbo-envoy** [comment]
做了啊， 添加后才会提示Ydv函数错误的，执行命令失败

**Comment by limbo-envoy** [comment]
这几个快捷键命令都会报不是编辑器命令

**Comment by VoldikSS** [comment]
建议把你的 vimrc 文件相关部分也贴过来

**Comment by limbo-envoy** [comment]
"有道翻译配置
vnoremap <silent> <C-T> :<C-u>Ydv<CR>
nnoremap <silent> <C-T> :<C-u>Ydc<CR>
noremap <leader>yd :<C-u>Yde<CR>

我是直接这么添加了啊

**Comment by VoldikSS** [comment]
map 用法不对

**Comment by limbo-envoy** [comment]
`"有道翻译配置
vnoremap <silent> <C-T> :<C-u>Ydv<CR>
nnoremap <silent> <C-T> :<C-u>Ydc<CR>
noremap <leader>yd :<C-u>Yde<CR>
`

**Comment by limbo-envoy** [comment]
![image](https://user-images.githubusercontent.com/30359746/47553445-bb16d880-d939-11e8-9f37-c60463d02b3e.png)

**Comment by VoldikSS** [comment]
哦我想起来了，**不是编辑器命令** 的错误根源应该是这里的几句
https://github.com/ianva/vim-youdao-translater/blob/785f2b5145ec54c70e557ae3134f7882c39ee8d5/plugin/ydt.vim#L40

可能是 Vim 版本太旧了？或者你没有安装上这个插件

**Comment by limbo-envoy** [comment]
我用的VIM - Vi IMproved 8.1，
![image](https://user-images.githubusercontent.com/30359746/47553564-0335fb00-d93a-11e8-8d2c-981121433f80.png)
插件也是直接从你github上clone过来的啊
