### ISSUE TITLE
Win10下neovim没有反应

### ISSUE THREAD

**Issue by kdurant** [ianva/vim-youdao-translater#35]
三个命令都没有反应
neovim0.4

**Comment by ianva** [comment]
Vim 8.0 以上版本使用 3.0 及以上版本（支持异步查询）    
低版本的 Vim，或者其他的非标准 Vim 如果出现问题请使用 [2.5.1 版](https://github.com/ianva/vim-youdao-translater/releases/tag/2.5.1)
