### ISSUE TITLE
windows下python3环境输出乱码

### ISSUE THREAD

**Issue by pangchol** [ianva/vim-youdao-translater#40]
个人在win10下的python3环境测试发现该插件输出会乱码, 该问题应该是由如下原因导致:
1. windows的gvim为了避免各种乱码一般会通过如下配置来设置vim内部编码统一采用utf-8编码:
set encoding=utf-8
 2. windows下的python3默认输出编码方式为gbk, 如果gvim设置了set encoding=utf-8,就会导致python3输出编码和vim内部编码不一致
3. 该情况可以通过对youdao.py文件添加如下逻辑解决:
```python
import io, platform
if __name__ == "__main__":
    if(platform.system()=='Windows'):
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer,encoding='utf8')
```

**Comment by voldikss** [comment]
欢迎提 Pull Request

**Comment by ianva** [comment]
如果可以的话请提交下 PR
