### ISSUE TITLE
在visual模式下，可以翻译单词，但无法进行语句的翻译，

### ISSUE THREAD

**Issue by mrbeardad** [ianva/vim-youdao-translater#44]
在visual模式下选取句子，插件提示“找不到该单词的释义”或“有道翻译查询出错”，可能是有道API的问题吧。因为不懂这这方面的知识，所以自己没法修改。希望作者大大能改进一下啦。
#27这是18年的了，嘿嘿，提个issue让您别忘记嘞

**Comment by ianva** [comment]
翻译句子这个有道的 API 已经废弃了，所以不 work 了，暂时不会对这个做修改，先 close 了
