### ISSUE TITLE
翻译返回的内容超过 command-line window 宽度时瞬间消失

### ISSUE THREAD

**Issue by hmgle** [ianva/vim-youdao-translater#7]
翻译某些词有时会出现看不到结果的情况, 原因是: 翻译返回的内容超过了 cmdmand-line window 的宽度, 显示的时候就不像其他情况那样了. vim 会临时更改 cmdwinheight 为可以显示内容的值, 然后在上面显示:
```
翻译内容
...
Press ENTER or type command to continue
```
而用户映射 `:Ydc` 的快捷键刚好是末尾带 `<CR>` 的, 这样导致 cmdwinheight 马上恢复为原来的 1, cmdmand-line window 重绘, 翻译内容瞬间消失, 用户无法看到翻译内容.

把 vim 窗口宽度拉小将很容易重新这个问题.

能否将翻译返回内容显示在 preview window 代替 cmdmand-line window 来避免这个问题?

**Comment by ianva** [comment]
cmdmand-line window 的初衷是不影响整个界面，不需要用户做多余动作，用 preview window 处理会需要有关闭的动作。
可以考虑增加一个配置可选使用  preview window

**Comment by wsdjeg** [comment]
> 而用户映射 :Ydc 的快捷键刚好是末尾带 <CR> 的, 这样导致 cmdwinheight 马上恢复为原来的 1, cmdmand-line window 重绘, 翻译内容瞬间消失, 用户无法看到翻译内容.

我在使用过程中没有遇到这样的问题,这是用户映射的问题,正常情况下只需要一个`<cr>` 来执行命令.

@hmgle 另外,如果有问题,最好是提供一个 reproduced way, 以及一个 minivimrc ,起码 一个map映射 配置

**Comment by wsdjeg** [comment]
可以尝试这样的map
`nnoremap <silent> <C-l> :Ydc<CR>`

**Comment by wsdjeg** [comment]
I have make a PR for this issue, and make the mapping works better.

**Comment by hmgle** [comment]
@wsdjeg Thanks. 更新按键映射后，没有问题了。

**Comment by wsdjeg** [comment]
@hmgle 不客气,这个插件,也是我每天用的比较多的一个.
